services:
    cb.application.abstract_application_service:
        class: CoreBundle\Application\Service\AbstractApplicationService
        abstract: true
        calls:
            - [setCommandBus, ['@cb.infrastructure.command_bus']]
            - [setEventBus, ['@cb.infrastructure.event_bus']]